<a href="https://colab.research.google.com/github/seko86/GIT/blob/master/071_080_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 71](#1)
* [Ćwiczenie 72](#2)
* [Ćwiczenie 73](#3)
* [Ćwiczenie 74](#4)
* [Ćwiczenie 75](#5)
* [Ćwiczenie 76](#6)
* [Ćwiczenie 77](#7)
* [Ćwiczenie 78](#8)
* [Ćwiczenie 79](#9)
* [Ćwiczenie 80](#10)

### <a name='0'></a>Import biblioteki

In [2]:
import numpy as np

np.random.seed(42)
np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 71
Podana jest poniższa tablica $A$:

```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
Od drugiego wiersza tablicy $A$ przestaw losowo wiersze w tablicy.

__Wskazówka:__ Użyj funkcji _np.random.shuffle()_.


In [6]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])

np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['001' '14.99']
 ['004' '2.49']
 ['005' '1.49']
 ['003' '7.99']]


### <a name='2'></a> Ćwiczenie 72
Podana jest poniższa tablica $A$:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Zwróć tablicę indeksów, które posortują tablicę $A$ rosnąco.

__Oczekiwny wynik:__


```
array([5, 2, 1, 0, 4, 3])
```
__Wskazówka:__ Użyj funkcji _np.argsort()_.



In [11]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

np.argsort(A)

array([5, 2, 1, 0, 4, 3])

### <a name='3'></a> Ćwiczenie 73
Podana jest poniższa tablica $A$:

```
A = np.random.randn(10, 8)
```

Zaokrąglij wartości tej tablicy do trzeciego miejsca po przecinku.

__Wskazówka:__ Użyj funkcji _np.round()_.

In [15]:
A = np.random.randn(10, 8)
A.round(3)

array([[-0.772,  1.661, -0.334, -0.318,  0.318, -1.612,  0.945,  1.266],
       [ 0.377,  1.651, -1.327,  1.844, -0.731, -1.28 , -0.237,  1.872],
       [-0.019, -0.933, -1.295, -0.105, -1.995, -1.3  ,  1.543,  1.323],
       [-0.128, -0.466,  0.059,  2.348,  0.405,  0.91 , -0.202,  0.061],
       [ 0.647,  0.126, -1.897,  1.281, -0.615,  2.111,  0.687,  0.071],
       [ 0.439, -0.108, -0.486,  0.208,  0.885, -0.465, -0.622, -0.355],
       [ 0.952,  1.453,  0.362,  0.581, -0.63 ,  0.877,  0.552, -0.71 ],
       [-1.788, -1.221, -0.669,  1.162,  1.553, -0.44 , -0.408,  0.262],
       [ 0.012,  0.931, -0.523,  0.949, -0.239,  0.854, -0.271, -0.613],
       [ 1.912,  1.065, -1.792, -0.447,  1.205, -1.197,  0.771,  0.667]])

### <a name='4'></a> Ćwiczenie 74
Wyznacz pierwiastki wielomianu:
* $W(x) = 4x^2 + 5x + 1$


__Wskazówka:__ Użyj funkcji _np.roots()_ oraz _np.polyval()_.

In [20]:
np.roots([4,5,1])

array([-1.  , -0.25])

Dokonaj sprawdzenia.

In [22]:
np.polyval([4,5,1], -1)
np.polyval([4,5,1], -0.25)

0.0

### <a name='5'></a> Ćwiczenie 75
Wyznacz pierwiastki wielomianów:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

__Wskazówka:__ Użyj funkcji _np.roots()_.

In [23]:
np.roots([2,4,-5,1])

array([-2.91610583,  0.65388685,  0.26221898])

In [25]:
np.roots([2,0,-5,1])

array([-1.67298165,  1.46961743,  0.20336421])

### <a name='6'></a> Ćwiczenie 76
Podane są wielomiany:

* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$


In [ ]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

Wykonaj działania:
* $W(x) + Q(x)$

In [28]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])

np.polyadd(W,Q)

array([2, 8, 0, 2])

* $W(x) - Q(x)$


In [29]:
np.polysub(W,Q)

array([-2,  0, 10,  0])

* $W(x) * Q(x)$


In [30]:
np.polymul(W,Q)

array([  8,  26,   2, -17,   0,   1])

* $W(x) + 2Q(x)$

In [32]:
np.polyadd(W,2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Ćwiczenie 77
Podana jest poniższa tablica:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```

Użyj funkcji znaku (_sign function_) dla tablicy $A$. Dla przypomnienia funkcja działa nastpująco: dla wartości ujemnych zwraca -1, dla zera wartość zero, dla wartości dodatnich 1.

__Oczekiwany wynik:__


```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```
__Wskazówka:__ Użyj funkcji _np.sign()_.


In [33]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Ćwiczenie 78
Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:


```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```



In [38]:
np.arange(np.datetime64('2021-01-01'), np.datetime64('2021-02-01'))

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')


### <a name='9'></a> Ćwiczenie 79

Wykorzystując funkcję _np.arange()_ wygeneruj poniższą tablicę:



```
array([['2021-01', '2021-02', '2021-03'],
       ['2021-04', '2021-05', '2021-06'],
       ['2021-07', '2021-08', '2021-09'],
       ['2021-10', '2021-11', '2021-12']], dtype='datetime64[M]')
```



In [37]:
np.arange(np.datetime64('2021-01'), np.datetime64('2022-01'))

array(['2021-01', '2021-02', '2021-03', '2021-04', '2021-05', '2021-06',
       '2021-07', '2021-08', '2021-09', '2021-10', '2021-11', '2021-12'],
      dtype='datetime64[M]')

### <a name='10'></a> Ćwiczenie 80

Wykorzystując funkcję _np.datetime64()_ wygeneruj dzisiejszą datę (datę w chwili robienia ćwiczenia).

In [44]:
np.datetime64('today')

numpy.datetime64('2020-06-16')